### ISSUE TITLE
Ethereum Token 

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#100]
Not all ERC-20 balances are shown.  According to Etherscan, there are 8 different ERC-20s including testnet rune.

![image](https://user-images.githubusercontent.com/82639838/115903061-fd8cd380-a417-11eb-9509-b0d67950c306.png)

![image](https://user-images.githubusercontent.com/82639838/115902881-c6b6bd80-a417-11eb-8846-1f684fec5ed6.png)

**Comment by skyorion427** [comment]
no need to display other testnet tokens since they are not usable without pools
