### ISSUE TITLE
Thorswap Showing an account balance although no wallet is connected.

### ISSUE THREAD

**Issue by Asghoig** [thorswap/thorswap-finance-app#103]
Thorswap.finance showing an active account balance of exactly "1000 RUNE equivalent" or so it would appear, even though no wallet is connected.

As can be seen in the screenshots, no wallet is connected, and I have never transferred any amount of RUNE to the Thorswap.finance platform, nor have I ever previously connected a wallet to such.

Furthermore, It does not appear that it matters which liquidity pool i check the status of, all of them have the same "1000 RUNE equivalent" balance appear. 

Additionally, it appears that it does not matter whether I have exclusively RUNE selected, the alternate pairing, or both, for the "1000 RUNE equivalent" to appear.

Let me know if you require any more context and I will do my best to provide such.

Best,

Asghoig

![Thorswap Finance_BugReport_04 28 2021](https://user-images.githubusercontent.com/83373747/116472402-de40dc80-a843-11eb-92c9-c9bbf28feb45.PNG)

![Thorswap Finance_BugReport_04 28 2021_V2_ETH](https://user-images.githubusercontent.com/83373747/116472407-df720980-a843-11eb-80db-88cd7bdedad5.PNG)

![Thorswap Finance_BugReport_04 28 2021_V3_ETH_ExclusiveEth](https://user-images.githubusercontent.com/83373747/116472929-89ea2c80-a844-11eb-856d-8eee096945f5.PNG)

![Thorswap Finance_BugReport_04 28 2021_V3_ETH_ExclusiveRUNE](https://user-images.githubusercontent.com/83373747/116472932-8a82c300-a844-11eb-8bec-8002dd21c002.PNG)

**Comment by thorswapdev** [comment]
that's not an actual amount and intended for the demo.
