### ISSUE TITLE
conversion btw ETH and BTC, way below from minimum received amount

### ISSUE THREAD

**Issue by ssh14** [thorswap/thorswap-finance-app#104]
![thorswapScreenshot 2021-04-29 144334](https://user-images.githubusercontent.com/83405645/116548067-5ff44100-a8fc-11eb-8d5a-1f7ec71377a5.jpg)

was expecting 0.0074 BTC received 0.0043 BTC
minimum received was 0.0070 BTC

**Comment by thorswapdev** [comment]
fixed now
