### ISSUE TITLE
couldn't send ETH to recipinent 

### ISSUE THREAD

**Issue by emmali73** [thorswap/thorswap-finance-app#113]
first of all, the actual amount of ETH i converted from RUNE is much lower than what i was told before i confirmed to swap. 2ndly, when i tried to send the ETH to recipient, nothing happened after I clicked on send. It kept on going back to the send screen. Pls advise what's going on?? Thanks,

**Comment by thorswapdev** [comment]
it's not an issue from thorswap/asgardex, but from ethplorer tool which is used for getting a wallet balance.
https://github.com/EverexIO/Ethplorer/issues/209
