### ISSUE TITLE
ETH Send not working when I'm connected to XDEFI Wallet

### ISSUE THREAD

**Issue by Batmine** [thorswap/thorswap-finance-app#116]
[**Describe the bug**](url)
When I send ETH in thorswap the extension crash and I get an error 

[**To Reproduce**](url)
1. Go to 'https://app.thorswap.finance/'
2. Connect your wallet XDEFI
3. Send ETH

[**Expected behavior**](url)
I should be able to send eth

[**Screenshots**](url)

https://user-images.githubusercontent.com/68971831/116258887-9f445580-a775-11eb-8790-8afedb093b2d.mov

[**Hardware**](url) 
- [x] PC
- [x] Mac

**Comment by drawbit** [comment]
fixed

**Comment by Batmine** [comment]
Thank you !
