### ISSUE TITLE
Fee - the shown fee is not accurate

### ISSUE THREAD

**Issue by ViorelG** [thorswap/thorswap-finance-app#122]
Please see photos
![Screenshot 2021-05-08 163854](https://user-images.githubusercontent.com/56368097/117546885-9d577d80-b024-11eb-80b6-23644285c29b.jpg)
![Screenshot 2021-05-08 163926](https://user-images.githubusercontent.com/56368097/117546886-9e88aa80-b024-11eb-8cfc-468b65dfc7fa.jpg)

It shows the fee is 3.674% but on calculation it is rather 7.299% .

**Comment by drawbit** [comment]
fees are fetched from thorchain oracle, not etherscan

**Comment by ViorelG** [comment]
Hi, I'm not sure why you mention Etherscan?? The screenshot is taken from thorchain, and the same numbers i've put them on on a percentage calculator app, and it shows in fact the difference in percentage.

**Comment by thorswapdev** [comment]
It was a wrong comment.

That's a slip percentage, not a fee percentage. You can refer details here:

https://docs.thorchain.org/how-it-works/fees
