### ISSUE TITLE
Leaderbord - RuneYield not working

### ISSUE THREAD

**Issue by ViorelG** [thorswap/thorswap-finance-app#123]
The page just keep loading and loading for hours, not displaying anything. Please see photo.
![board](https://user-images.githubusercontent.com/56368097/117547039-65046f00-b025-11eb-91a3-693e1a180c7b.jpg)

**Comment by drawbit** [comment]
not thorswap issue

**Comment by ViorelG** [comment]
Can you please tell me where can i address it instead, or if you could please submit it where it should? Thank you.
