### ISSUE TITLE
Offline signing for traders and liquidity providers

### ISSUE THREAD

**Issue by crocket** [thorswap/thorswap-finance-app#129]
Offline signing would improve security greatly. It also doesn't depend on hardware wallets.
Achieving great security without having to rely on hardware wallets is great.

A password-encrypted keystore wallet contains just a private view key. A small command line wallet creates a keystore wallet on an offline machine and export a view-only keystore wallet from it. Thorswap can create unsigned transactions. The command line wallet can sign transactions offline. Thorswap can broadcast signed transaction.

A few things to figure out in order to implement offline signing

* How keys are structured in a keystore wallet
* Where keys are used
* How keys are constructed and used

I can help with development of a tiny command-line wallet dedicated to creating an offline wallet and signing transactions offline.

**Comment by bullishtrader** [comment]
Hey @crocket , thanks for this report.
The idea is great.

Altough now there is a wide offer of different wallets.. Soon we will be able to use Ledger with native RUNE as well.
Definitely Ledger is going to be the most secure wallet.

Have a great day

**Comment by crocket** [comment]
Can you explain why this issue is closed? Monero supports both offline signing and hardware wallet.

**Comment by ldwrs** [comment]
It would also be great for everyone already providing liquidity.  This shouldn’t have been closed.

**Comment by crocket** [comment]
Offline signing is secure and flexible. Even if ledger dies off as a company or a product, offline signing can live on as long as thorswap is available. Also, offline signing can utilize an old computer while ledger should be bought separately.

**Comment by crocket** [comment]
I wonder whether offline signing is something developers are willing to merge if someone else implements it for them.
