### ISSUE TITLE
adding liquidity on BUSD

### ISSUE THREAD

**Issue by Jaxxou** [thorswap/thorswap-finance-app#13]
Hello,

I can't add liquidity for BUSD:RUNE, doesn't show my pool balance

![Capture](https://user-images.githubusercontent.com/78721473/113984407-2039bc80-985c-11eb-8e50-07563bd6cc03.JPG)

bnb16g22ty7974vsez06phd5hy6ulwx7zkctzy8sds

**Comment by boxofscraps** [comment]
There is two different BUSD.  One has a liquidity pool and the other does not.  Make sure you are adding on:
https://thorswap.finance/swap/BNB.BUSD-74E_THOR.RUNE

**Comment by skyorion427** [comment]
fixed
