### ISSUE TITLE
ThorSwap not reading balances from Ethereum Chain

### ISSUE THREAD

**Issue by cruz660** [thorswap/thorswap-finance-app#130]
Imported seed phrase to create a Keystore. After connecting the Keystore to ThorSwap, it is not reading anything from the Ethereum chain (see attached screenshot) despite balances of 0.18 Ether and 725 USDT tokens, as shown on Etherscan here:
https://etherscan.io/address/0x9ae9e2bfb9179d78bbb879b4e18c068cc229eca2

![Screenshot 2021-05-04 000528](https://user-images.githubusercontent.com/59448250/117822107-cd11ba00-b29e-11eb-94c9-edf162750735.jpg)

**Comment by drawbit** [comment]
fixed
