### ISSUE TITLE
cannot select BUSD on the adding liquidity

### ISSUE THREAD

**Issue by Jaxxou** [thorswap/thorswap-finance-app#14]
when i try to click on busd for adding liquidity, 

it doesn't work, i must go to the main page to get it and add liquidity. 

![Capture](https://user-images.githubusercontent.com/78721473/113984916-a950f380-985c-11eb-954b-a33a875553a1.JPG)

bnb16g22ty7974vsez06phd5hy6ulwx7zkctzy8sds

**Comment by skyorion427** [comment]
fixed
