### ISSUE TITLE
For the add liquidity tab, the slider under rune does not move when adding rune only

### ISSUE THREAD

**Issue by hodlgod69** [thorswap/thorswap-finance-app#15]
After accessing the add liquidity tab, when adding rune only, the slider does not display the amount of rune added. It displays the asset being added only. This bug does not exist when adding asset, or when adding both asset or rune.

![image](https://user-images.githubusercontent.com/82140684/113985002-453f2700-987e-11eb-9b35-33b773ceca2d.png)

Rune value not displayed, and not added when adding rune only to liquidity pool.

What it was for other options: adding btc and rune

![Untitled 2](https://user-images.githubusercontent.com/82140684/113985412-b4b51680-987e-11eb-8367-c3a36220c4a4.png)

When adding btc only

![Untitled 3](https://user-images.githubusercontent.com/82140684/113985620-f3e36780-987e-11eb-948a-8a129f7f192d.png)

This bug is also in other pools like eth pool and bnb pool and possibly all other pools as well.

**Comment by skyorion427** [comment]
fixed
