### ISSUE TITLE
Support Create Liquidity

### ISSUE THREAD

**Issue by thorswapdev** [thorswap/thorswap-finance-app#151]

**Comment by kicksydk** [comment]
Hi, I am having some issues.
I deposited  14 ETH 0x832459ac11FF69af33bf153Cee3E7D6Ca42e78f2
I was trying to add ETH + RUNE to the LP
It showed transaction from XDEFI wallet failed on a number of attempts
I now see that nearly all my ETH has gone from my balance, but I cant find any trace within Torchain.finance
Contracts showing if you follow the trail, but not populated my balance  
Here is one of the 4 0x42A5Ed456650a09Dc10EBc6361A7480fDd61f27B
Can you advise on whats going on?

**Comment by thorswapdev** [comment]
> Hi, I am having some issues.
> I deposited 14 ETH 0x832459ac11FF69af33bf153Cee3E7D6Ca42e78f2
> I was trying to add ETH + RUNE to the LP
> It showed transaction from XDEFI wallet failed on a number of attempts
> I now see that nearly all my ETH has gone from my balance, but I cant find any trace within Torchain.finance
> Contracts showing if you follow the trail, but not populated my balance
> Here is one of the 4 0x42A5Ed456650a09Dc10EBc6361A7480fDd61f27B
> Can you advise on whats going on?

Join discord and open the ticket

**Comment by kicksydk** [comment]
Do you know the discord 4 digit channel code? 
I keep getting an error message that my invite has expired

**Comment by kicksydk** [comment]
Discord not giving me access, says invite expired or invalid constantly

**Comment by kicksydk** [comment]
https://discord.com/invite/PX4MNV5F

This is an expired invite code that is being generated

**Comment by thorswapdev** [comment]
Use this one

https://discord.gg/K7QR9rdM

**Comment by kicksydk** [comment]
Thank you, have raised a ticket in Discord

**Comment by bullishtrader** [comment]
done
