### ISSUE TITLE
FIX - "Pool Share Estimated" information icon (i)  

### ISSUE THREAD

**Issue by bullishtrader** [thorswap/thorswap-finance-app#153]
![unknown](https://user-images.githubusercontent.com/82927810/118160418-919df980-b41e-11eb-816b-52ab03c29acd.png)

**Comment by bullishtrader** [comment]
WRONG INFORMATIONS - It shows "Estimated time to process the transaction" instead of Pool Share estimated

**Comment by thorswapdev** [comment]
Fixed
