### ISSUE TITLE
cant select USDT from binance chain on adding liquidity 

### ISSUE THREAD

**Issue by Jaxxou** [thorswap/thorswap-finance-app#16]
when i try to select USDT from binance chain on adding liquidity it doesn't work, 

![Capture](https://user-images.githubusercontent.com/78721473/113986157-fa151c00-985d-11eb-8c2c-ab5962c58fa4.JPG)

bnb16g22ty7974vsez06phd5hy6ulwx7zkctzy8sds

**Comment by skyorion427** [comment]
fixed
