### ISSUE TITLE
Impossible to activate new pools

### ISSUE THREAD

**Issue by TreefeedXavier** [thorswap/thorswap-finance-app#169]
https://user-images.githubusercontent.com/6923053/118805507-a8c16900-b8ae-11eb-8024-535a1ade5158.mp4

It is impossible to add new pools on bep2 and ERC20 chains - UI just dissappears.

**Comment by 0xLuc** [comment]
There is currently no TWT pool on MCCN, to create or list a new asset please see: https://docs.thorchain.org/how-it-works/governance

**Comment by TreefeedXavier** [comment]
I know that there no TWT pool. UI should redirect user to "create a pool" page, not to blank one.

**Comment by 0xLuc** [comment]
@TreefeedXavier I now realise I made an mistake, you are correct (I assumed you wanted to add towards a liquidity pool) vs open a new pool. I get the same blank page as you. Will update label to enhancement.

Sorry for the earlier confusion

**Comment by bullishtrader** [comment]
This is working properly, wait for #RAISETHECAPS to create a new pool.
