### ISSUE TITLE
Graphics very tall on mobile

### ISSUE THREAD

**Issue by ricoCryptoboy** [thorswap/thorswap-finance-app#17]
![42E2F69E-D15E-4AC9-81C1-CB5550FE40E9](https://user-images.githubusercontent.com/82144207/113993204-799ded80-9854-11eb-8aec-2613426fbf15.png)
Hi, 

need adjustement of volume and others graphics size on IOS they take many screens.

**Comment by skyorion427** [comment]
Fixed
