### ISSUE TITLE
Withdrawal pending

### ISSUE THREAD

**Issue by vmicic** [thorswap/thorswap-finance-app#170]
Added RUNE to BTC/RUNE pool asymmetrically. 
https://viewblock.io/thorchain/tx/85C8190DC100CC77D06C53BE2DD7A923F453038BD821625AAC1950F94FCF1A37

Tried to withdraw BTC asymmetrically (didn't know this wasn't possible).
https://viewblock.io/thorchain/tx/F773C91410E45329A3617B2AA60298EC718FA79FF9AEA0FA6C0EC043009C6C3E

Withdraw is still pending and I haven't received any funds for more than 24 hours.

**Comment by storm-breaker2** [comment]
User deposited a total of 901 RUNE asymmetrically to the BTC pool and tried withdrawing BTC asymmetrically.  It seems 
75165827362 LP Units + 65876868038 LP Units were deposited but the transaction is still pending:
https://thornode.thorchain.info/thorchain/tx/F773C91410E45329A3617B2AA60298EC718FA79FF9AEA0FA6C0EC043009C6C3E/signers

**Comment by 0xLuc** [comment]
Any update on why the tx hasn't been processed, or is there a way to cancel the withdrawal?

**Comment by vmicic** [comment]
Can you look at this? 

It's been a week, and I'm still missing my funds.

**Comment by thorchain-admin** [comment]
@vmicic just to clarify

1) you added *assym* (ie, with just a RUNE address) into the BTC pool. 
2) you then instructed to withdraw *assym* to BTC, however, the state machine does not have your BTC address, so it cannot do so properly

It seems to have swallowed it

**Comment by vmicic** [comment]
That makes sense, I wasn't aware you couldn't do that.

Thank you for your response, I hope you'll be able to recover funds.

**Comment by thorchain-admin** [comment]
This is confirmed a bug, reach out to @kkkilo on tg for refund

**Comment by vmicic** [comment]
I will, thank you, you were all very helpful.

**Comment by cbarraford** [comment]
a bugfix for this issue is here
https://gitlab.com/thorchain/thornode/-/merge_requests/1724

**Comment by bullishtrader** [comment]
User contacted Kkkilo on TG for the refund.

User should have received the refund.
Issue is fixed
