### ISSUE TITLE
Thorswap doesn't show possible swaps

### ISSUE THREAD

**Issue by LM40357365** [thorswap/thorswap-finance-app#176]
Thorswap does not possible swaps when I don't have the funds in my wallet or don't have a wallet connected. For certain things - like arbitrage opportunities - it would come in handy if it does show the possible swap amounts. To my knowledge, this was possible a couple of days ago. See the screenshot below. 
![ice_screenshot_20210520-210149](https://user-images.githubusercontent.com/84539729/119034614-d261b980-b9ae-11eb-8e04-ea1a564f5019.png)

**Comment by thorswapdev** [comment]
fixed
