### ISSUE TITLE
ETH.USDT to Rune Swap using MetaMask not possible... always get "Approve failed"

### ISSUE THREAD

**Issue by add2it** [thorswap/thorswap-finance-app#181]
When trying to swap ETH.USDT from an Exodus wallet using MetaMask to Thorchain Rune, it always fails with the message "Approve failed." seconds after clicking the Approve button.

There is sufficient ETH in the wallet for gas fees.

The swapping ETH to Rune from the same wallet works fine... Approve is not needed there.

I tried this in the latest versions on Brave, Chrome, and Firefox on macOS Mojave.

![](https://www.evernote.com/l/ADKNC4mtAElHkoiQ9HTeMCF3FPNAiUzTKl0B/image.png)

![](https://www.evernote.com/l/ADJa1bDnIUREXpH5QHUqoUmBQmZF2S8kudcB/image.png)

![](https://cdn.discordapp.com/attachments/846048865303265351/846076163762946098/Settings__About_Brave.png)

![](https://cdn.discordapp.com/attachments/846048865303265351/846107553951514654/About_This_Mac.png)

**Comment by 0xLuc** [comment]
Another user reported issues with Brave + metamask (native), while approving SNX on thorswap (ticket-485).

**Comment by 0xLuc** [comment]
@add2it did you experience the same issues lately?
