### ISSUE TITLE
ADD — Warning messages

### ISSUE THREAD

**Issue by bullishtrader** [thorswap/thorswap-finance-app#184]
Add a warning message when users deposit again in the pool in the 100 days timeframe.

i.e: Be aware that If you add liquidity again in case you're eligible for ILP, your protection will be resetted.

**Comment by Kapot** [comment]
+1. I would have know the LP protection will reset before adding more to the pool.

Added a screenshot for visualization. 

![thorswap warning](https://user-images.githubusercontent.com/6935358/119637825-59cb8480-be16-11eb-9044-331bda816d8f.png)

**Comment by bullishtrader** [comment]
> +1. I would like to have know the LP protection would reset before adding more to the pool.
> 
> 
> 
> Added a example of the message for visualization.
> 
> 
> 
> ![thorswap warning](https://user-images.githubusercontent.com/6935358/119637825-59cb8480-be16-11eb-9044-331bda816d8f.png)
> 
> 

Check ADD Warning message (2) is there 😄

**Comment by bullishtrader** [comment]
If wallet does not support native RUNE or hold RUNE, warn/prompt user when trying to LP symmetrically. Present the option for asset to be added asymmetric or prevent the attempted deposit.

Currently, an error is shown after attempted add “Error: Phrase Not Set” and only the transaction that was signed for is added.
