### ISSUE TITLE
IL protection not showing up 

### ISSUE THREAD

**Issue by dmny420** [thorswap/thorswap-finance-app#187]
Unable to view current level of IP protection. Have two LPs (44 day and 22 day). Both show 0.000 for both Rune and Asset. Thanks.

**Comment by bullishtrader** [comment]
Hey @dmny420 .
Please can you open a ticket in the Help Desk on Discord so we can check further into this and clarify any concern you may have? Thank you.

**Comment by bullishtrader** [comment]
I'll close this ticket as does not seem to be an issue with THORSwap, keep in mind that if you are LP'ing on BEPSWAP there is no ILP if you have not been in the pool for more than 100 time.

If your are LP'ing on MCCN - THORSwap, if you cannot see ILP is for 2 reasons:

1. You do not need ILP.

2. There is some bug with Runeyield calculating your ILP.

Feel free to open a ticket on discord and ask for The Bull if you need additional help and have further questions.

Regards
