### ISSUE TITLE
Pools Icon not displaying properly

### ISSUE THREAD

**Issue by runekeithrun** [thorswap/thorswap-finance-app#19]
![Capture1](https://user-images.githubusercontent.com/82149388/114008770-239d6a00-9895-11eb-9c48-8dcb7d138bac.PNG)

When we go to the "Pools" feature on the right panel, the "DAI", "SAT", "USDT", and "BUSD" icon is not displaying properly.

**Comment by skyorion427** [comment]
Forwarded issue
https://github.com/asgardex/asgard-exchange/issues/227
