### ISSUE TITLE
Wallets: Another option

### ISSUE THREAD

**Issue by malmod** [thorswap/thorswap-finance-app#196]
I am just playing with Thorswap and awating xDefi and wanting to try cross-chain swaps/pools, it is my understanding that the Keystore is the only option.

In terms of security, however, having the app itself manipulate the private key and sign the transaction seems not optimal for larger amounts. The frontend may be hacked, etc.

Do you think it would be worth to implement a safer option for using the keystore, for instance running a local node/deno service that holds the key and signs the transaction?

**Comment by bullishtrader** [comment]
Hey @malmod keystore is not the only option on THORSwap.

You can use: 

-XDEFI (store, receive and send NATIVE RUNE and other assets)

- TrustWallet via Wallet Connect, still not possible to store native RUNE Though.

- Ledger (Only binance chain ATM)

- Metamask (Only ERC20 - If you want to trade ETH for Native RUNE you will need to input a NATIVE RUNE address.

- Keystore Wallet (Any asset)

Native RUNE is coming very soon on TrustWallet and Ledger, and in terms of security keystore is recommended as temporary option.

Regards

**Comment by malmod** [comment]
Thanks @bullishtrader 

Let's say I want to pool native BTC / native RUNE. xDefi does not seem to be yet available and indeed all the other options won't work, so the Keystore is the only option.

What I mentioned would still be a longterm good solution for people who can launch a local service by themselves (note that local cors may require `local-cors-proxy`) as an alternative to Ledger (I'd like one but I'd rather be sure my home address won't be all over the Internet first :).

**Comment by bullishtrader** [comment]
Yep exactly.
Ledger integration is coming soon but at the start there will be only native RUNE, I think more chains will be added later on.

Stay tuned for further announcements and also, feel free to reach me out on discord if you have further questions
