### ISSUE TITLE
UI -> Does NOT detect when switching from ETH to BSC in METAMASK.

### ISSUE THREAD

**Issue by bullishtrader** [thorswap/thorswap-finance-app#198]
**User reported this issue:**

_I was using_ https://app.thorswap.finance/ _to convert ETH -> BNB, with MetaMask wallet._ 
_I exchanged 0.05 ETH I have both Ethereum and Binance Smart Chain in MetaMask._ 
_Before I clicked submit, I switched to Binance Smart Chain in metamask._ 
_Thorswap did not detect this change, and sent 0.05 BNB instead when I clicked Submit._ 

This money just got stuck somewhere.

**Here's the tx:**
https://bscscan.com/tx/0x7e10c74b8c760219ef2824abe400bb5934c8ad5a1d758b6a1cf18c97e7629085

**ETH Address**
0x41c8dc0628d773c2b65b7d632f7dfb00a245fc66

Thorswap should detect that you're on the correct network before sending out funds

**Steps to reproduce the issue:**

- Connect metamask to Ethereum network
- Log onto ThorSwap, do an ETH -> BNB transaction
- Before clicking Submit, switch metamask to BSC
- Click submit

THORSwap should have a warning not allowing user to switch the network.

**Comment by storm-breaker2** [comment]
hmmm .... I not sure if this is possible.

**Comment by bullishtrader** [comment]
> hmmm .... I not sure if this is possible. 

It's a weird issue tbh.

Why users would do this?
