### ISSUE TITLE
Creating a wallet gives you 2 text files instead of 1

### ISSUE THREAD

**Issue by DiamondHanz** [thorswap/thorswap-finance-app#2]
Hi,
I tried creating a wallet and found a small bug.

When creating a wallet it gives you 2 text files instead of 1.

**Comment by skyorion427** [comment]
@DiamondHanz , could you provide the reproduce steps?

- OS platform
- browser (Chrome, Safari, etc)

**Comment by DiamondHanz** [comment]
> @DiamondHanz , could you provide the reproduce steps?
> 
>     * OS platform
> 
>     * browser (Chrome, Safari, etc)

Yes, sure.

Connect (Right upper corner) > Create wallet > Enter password (twice) and click "create" after it generates two text files.

OS: MacOS Big Sur 11.2.3
Browser: Firefox 87.0

**Comment by arwyn6969** [comment]
same for me Mac OS 10.13.06 they are different sizes. one 556k one 559k

**Comment by skyorion427** [comment]
fixed
