### ISSUE TITLE
Update PENDING Pools Message (i)

### ISSUE THREAD

**Issue by bullishtrader** [thorswap/thorswap-finance-app#201]
**This message should be updated:**

![unknown](https://user-images.githubusercontent.com/82927810/120098696-b345f300-c137-11eb-914c-90072057c549.png)

**1)** It is 43200 blocks (2,5 days) - it is better to take it from POOLCYCLE variable on https://midgard.thorchain.info/v2/thorchain/mimir

**2)** Add important condition: "*the pool with the most liquidity and at least 20k Rune depth.* (**10k Rune and 10k Rune equivalent in asset**) *wins*"

**3)** Add: *Pending pools should pay 'pending fee' 10 RUNE per cycle (43200 blocks)*

**Comment by thorswapdev** [comment]
nice suggestion!

updated
