### ISSUE TITLE
UI BUG - Browser Notification of Transfer in Progress Doesn't Change/Stop when Swap is Completed

### ISSUE THREAD

**Issue by morgandrmaj** [thorswap/thorswap-finance-app#209]
Hi and thanks to the Devs for all your hard work!

I've experienced this bug a couple of times and wanted to pass it along.  

It's a Browser UI bug in the notifications about a swap completing.  

Conditions: 
- I was swapping on Thorswap between coins.  In this case it was USDT to Rune.  
- Using both trust wallet and XDefi Wallet.  
- Chrome browser on a Mac

Situation:
I confirmed the swap through and get the notification that it was processing in the upper right.  
The notification spins for an inordinately long amount of time and doesn't confirm.
I check my wallet (via the Thorswap wallet window) and it shows clearly that the coins have arrived just fine.  
The notification doesn't complete and keeps spinning.  

I think this has happened to me on 3 different occasions in the last week.  I didn't take notes on the other situations so I can't help in the replication in the other cases.  

Enclosed here is the image in my upper corner.  
(It continues spinning and never stops.)

Not a big deal in terms of functionality, but I expect that it's you folks will want to sort out.  

Thanks for all your hard work on making the ThorChain awesome

![Screen Shot 2021-05-31 at 2 16 26 PM](https://user-images.githubusercontent.com/11479863/120245492-36437800-c222-11eb-9bb4-8ea541d4f4c6.png)

**Comment by morgandrmaj** [comment]
FYI -- It happened to me again tonight.  Essentially the same as last time.  This time it was KYL -> RUNE. Here's a screen shot.

<img width="422" alt="Screen Shot 2021-06-02 at 12 01 22 AM" src="https://user-images.githubusercontent.com/11479863/120438320-12715680-c336-11eb-9369-a1f8fb900d18.png">

**Comment by bullishtrader** [comment]
Hello @morgandrmaj , Thanks for your report.

Apparently on Firefox seems to work better.
We are working on an "auto refresh" on all pages which should fix this issue.

Next time this happen to you i recommend to refresh your browser or to disconnect & reconnect your wallet.

The auto refresh should be implemented soon :)

Have a great day!

Regards
