### ISSUE TITLE
Layout not standardise when we select "Midgard Explorer"

### ISSUE THREAD

**Issue by runekeithrun** [thorswap/thorswap-finance-app#21]
![Capture3](https://user-images.githubusercontent.com/82149388/114010303-8cd1ad00-9896-11eb-9b7e-bb6cafdd41ac.PNG)
![Capture4](https://user-images.githubusercontent.com/82149388/114010415-ab37a880-9896-11eb-8331-4530516aada9.PNG)

The right panel layout is actually standardised for "Overview", "Nodes", "Network", etc... except "Midgard Explorer"

**Comment by skyorion427** [comment]
Forwarded issue to asgardex team

https://github.com/asgardex/asgard-exchange/issues/227
