### ISSUE TITLE
Wallet Connect iOS

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#219]
User reported mobile trust wallet connect does not work.  User seemed directed to wc website instead of trustwallet wallet connect. 

https://user-images.githubusercontent.com/82639838/120862071-2dfa7e00-c53d-11eb-931d-4394efd81623.mov

**Comment by bullishtrader** [comment]
This seems to be an issue with TW not with THORSwap.
TW can't detect its own app on the phone.

Wallet Connect is working perfectly on iOS through Safari, Chrome and Brave
