### ISSUE TITLE
Added BTC liquidity not showing

### ISSUE THREAD

**Issue by aang0203** [thorswap/thorswap-finance-app#22]
Added liquidity to the BTC pool, but it is not showing in either the withdraw tab or show liquidity tab. 
![Screenshot 2021-04-08 at 10 45 11 AM](https://user-images.githubusercontent.com/82150468/114010840-760e6480-985c-11eb-93b2-3778e83cfd3c.png)

**Comment by boxofscraps** [comment]
Does it show up under:
https://thorswap.finance/liquidity

**Comment by aang0203** [comment]
Ah it does now; it didn't when I posted it.
