### ISSUE TITLE
Ledger + Chrome broken

### ISSUE THREAD

**Issue by demian85** [thorswap/thorswap-finance-app#221]
How to reproduce?
Using Mac + Chrome 91 + Ledger on Thorswap. Click on connect, plug in Ledger and open Binance Chain app. Select Ledger and choose Binance Chain, nothing happens.

It seems that Chrome either deprecated an API or introduced a bug in the WebUSB API.
This relatively new API appears to be the solution from now on: https://developer.mozilla.org/en-US/docs/Web/API/WebHID_API
Source: https://www.reddit.com/r/ledgerwallet/comments/noqncy/connecting_ledger_nano_x_to_adaliteio_via_webusb/

Please check it out.

**Comment by bullishtrader** [comment]
Thanks for the report @demian85 

A temporary solution is to use Firefox for now.

**Comment by bullishtrader** [comment]
UPDATE: Ledger will soon publish an update for this issue.
I'll close this issue for now, as mentioned above the workaround is to use Firefox browser for now.

There should be an update from Ledger later this summer.

**Comment by demian85** [comment]
I thought the issue was the deprecated API in Chrome, as everybody said. If Ledger was the issue, why Firefox works?
Never mind, I didn't even try to fix this. No time.

**Comment by bullishtrader** [comment]
@demian85 yes, ledger should fix this issue releasing an update for the new Chrome version (the latest)
We will be using Firefox for now while we wait for the update
