### ISSUE TITLE
Ticket-838 | ERROR: Out of gas in location: readperbyte

### ISSUE THREAD

**Issue by bullishtrader** [thorswap/thorswap-finance-app#224]
![image](https://user-images.githubusercontent.com/82927810/121594174-fe67dc00-ca3c-11eb-96c6-abec1694e6ec.png)

User Tried to withdraw from BNB pool. 

User have RUNE +  BNB in the wallet and he's Getting this error.

Same issue on Asgardex.

**transaction hash:**
7A44E44F5C3D1C3B65B0749DE3934395884AABA0AE9629915C41C3B7EBB4B232

**Thor Address:**
thor1anzpcqcanagcplxq7ppc7cveueg097d0594k9g

wallet holds 1 RUNE + 1 BNB. 

User is using XDEFI Wallet to withdraw.

**Comment by bullishtrader** [comment]
Fixed

**Comment by 0xLuc** [comment]
Re-opening the issue as it has appeared again in the following two tx's (both on xdefi and keystore)
[Sym] ETH | Rune LP withdrawal
Xdefi:
025C71EE81617D80335F6F5D9542586B5022826C73C0B889D32B59F69BF547FC

Keystore
C49064CF7F8144B486B5D0EB988E6AF11E7AFCD67C77526E17F9AA33A0985CDF

**Comment by thorswapdev** [comment]
Anothre Failing tx: https://thornode.thorchain.info/txs/38ED2D508DC30310FBC8652486C1AF3F7F1193F0290CDDED794891182BE5A7DF

**Comment by thorswapdev** [comment]
should be fixed
