### ISSUE TITLE
BUG - Thorswap Wallet UI Has an Update Delay

### ISSUE THREAD

**Issue by morgandrmaj** [thorswap/thorswap-finance-app#226]
Hi folks,

There's currently a delay between when tokens show up in my external (connected) wallets and when they appear in the Thorswap UI of my wallet.  I'm noticing this pretty much every time I do a token swap on another site.  (i.e. the Thorswap UI isn't in sync with what my wallets show as my new tokens.)  This happens with both the XDEFI wallet and Trust Wallet.  Refreshing wallets (TW, XDEFI or Thorswap UI refresh) doesn't resolve it.  Restarting browser doesn't solve it.  Only time seems to?  Not sure.  

Sometimes it seems that if I switch to Brave, it resolves it, but I think that might just be the time it takes to get the new browser up.  I'm wondering if there's some sort of update that the system does on a refresh rate, but doesn't necessarily do it as often as the wallets do so things occur as out of sync?

This is unusual behaviour that doesn't happen on other swap sites.

It also means the user needs to wait to swap.  Usually not more than a couple of minutes, but it's long enough for prices to change.

Here's an example scenario that I've seen dozens of times:
(As an FYI - I'm working on an arb bot, and have been working through a number of manual arbitrage transactions.) 

If I use my XDEFI wallet to swap to a new token (for example SUSHI -> USDT) on an external site (like Uniswap) and then I disconnect and connect my wallet over on Thorswap after the transaction has completed, my XDEFI wallet UI shows the new USDT.  
But the Thorswap UI of my wallet shows none of the new USDT, just the Sushi -- which no longer exists in my wallet.  
Refresh doesn't help - refreshing both/either Thorswap or XDEFI.
Restarting Chrome doesn't help.
Time seems to help.  Usually its 1-2 minutes.

Note that this happens on Thorswap with all major swap sites that I've tried --  Uniswap, Sushiswap, 1inch, etc.
Note also that this happens with both the XDEFI and the Trust Wallet.
Note also that this doesn't happen when I swap on the competitor sites - Uniswap, Sushi, 1Inch, etc all stay in sync with the wallets with no delay.

Let me know if I can provide more specifics or if you need more details. 
I could even record a video to show you how it's occurring next time I run some manual transactions.

**Comment by bullishtrader** [comment]
Hi @morgandrmaj , This issue is normally caused by a delay with the API we are using.

Sochain API is running out of sync ATM, so Interfaces could experience balance delays and UTXOs issue for the next few days.
Recently we found a fix where the balance was not updating AT ALL even though the explorer was showing the correct balance in the wallet.
There might be delays, and i am sorry for any inconvenience.

![Schermata 2021-06-12 alle 10 13 31](https://user-images.githubusercontent.com/82927810/121770001-04f27280-cb67-11eb-97e2-2080209a9467.png)

- https://sochain.com/

Eventually, we will find an alternative solution for this issue.
Thanks

Regards

**Comment by morgandrmaj** [comment]
Awesome.

Thanks for the info. Glad to hear that you guys know about the issue.

Wasn’t sure if I was stressing the system in an unusual way and wanted to pass it along.

Have a great night. 

M
