### ISSUE TITLE
withdraw : Tx Pending

### ISSUE THREAD

**Issue by Ccoepio** [thorswap/thorswap-finance-app#229]
Hello, i'm trying to withdraw some Rune-BTCB, but the tx said it's " out of gas". Thank you for your help. 
https://viewblock.io/thorchain/tx/B3F1244FAF1887DD855A50F2C4F789D21103BC9FC821F2C367F7EA97FD79233B

**Comment by bullishtrader** [comment]
Hi @Ccoepio we released a fix for this issue yesterday, do you mind opening a ticket on Discord so we can look further into it?
Thanks

Join here: https://discord.gg/jqK3NEme
