### ISSUE TITLE
Adding RUNE overnight

### ISSUE THREAD

**Issue by aang0203** [thorswap/thorswap-finance-app#23]
Added RUNE last night, but it is still processing up till now
![Screenshot 2021-04-08 at 11 21 15 AM](https://user-images.githubusercontent.com/82150468/114010970-9c340480-985c-11eb-8c8c-e6068a349630.png)

**Comment by skyorion427** [comment]
Did you add Native RUNE?

**Comment by aang0203** [comment]
Hi @skyorion427 ,
that was the first thing I did after I got all my RUNE, so all RUNE is native.

**Comment by skyorion427** [comment]
fixed
