### ISSUE TITLE
Pending pool < 1000 rune is not getting asset price updates

### ISSUE THREAD

**Issue by 0xLuc** [thorswap/thorswap-finance-app#232]
The LINK | RUNE pool is not getting price updates and is below the minimum required 1000 RUNE.

It's currently reporting a price of ~ 5.5$ while the actual LINK price is around 25$

https://app.thorswap.finance/pool/ETH.LINK-0X514910771AF9CA656AF840DFF83E8264ECF986CA

**Comment by 0xLuc** [comment]
Changed from bug to feature request
Please add warning for users that price might be outdated compared to actual prices on the market.

**Comment by DreamboatCrypto** [comment]
Quick question on this. If thorchain continues to think the price of LINK is $5.5, how will the pool ever attract enough deposits to open? Depositing when one of the assets if mispriced this badly is dangerous, so this pool seems to be doomed to stay pending forever, no?

**Comment by DreamboatCrypto** [comment]
Checking on the LINK pool again, the price of link is now $1.73, off by about 93%.

**Comment by DreamboatCrypto** [comment]
@bullishtrader @0xLuc

I'm thinking this probably shouldn't have been changed from bug to enhancement request.
