### ISSUE TITLE
Metamask ETH withdrawal bug

### ISSUE THREAD

**Issue by Jonnyiswinning** [thorswap/thorswap-finance-app#238]
there is a 
- Metamask withdrawal bug for ETH LP
That when I try to withdraw ETH asymmetrically from the LP that no matter what amount (%) you try to withdraw that metamask only lets me withdraw 0.00000001 Ether

TXID

https://viewblock.io/thorchain/tx/237FF736F09890E184C7A19E0BA5105C9E55A71EA436A000B7F0D926F05A0FD8

https://etherscan.io/tx/0x237ff736f09890e184c7a19e0ba5105c9e55a71ea436a000b7f0d926f05a0fd8

![image](https://user-images.githubusercontent.com/86065363/122420870-9a1fad80-cf51-11eb-916e-ecae9dd15f50.jpeg)

![image](https://user-images.githubusercontent.com/86065363/122421165-d05d2d00-cf51-11eb-8c6d-bee82e0382ed.jpeg)

![image](https://user-images.githubusercontent.com/86065363/122423166-54fc7b00-cf53-11eb-8977-410d2b9f6fa6.jpeg)

![image](https://user-images.githubusercontent.com/86065363/122423211-5e85e300-cf53-11eb-9093-37072a80e53b.jpeg)

**Comment by bullishtrader** [comment]
This is fixed
