### ISSUE TITLE
Question // Is offline signing something that developers are going to merge?

### ISSUE THREAD

**Issue by crocket** [thorswap/thorswap-finance-app#244]
If it is and I have some time, I may write code and submit pull requests.
If it is not, I will look for other projects or perhaps create a (curses) terminal thorchain frontend...
This issue is just a questionnaire to gauge acceptance. This issue is not meant to be left open for a long period of time.

I want to first make sure that I don't spend a lot of time on something that doesn't have a pretty good chance of being merged.

Offline signing means creating a keystore view wallet and a private key on an offline computer, creating an unsigned transaction, signing it on an offline computer, and submitting the signed transaction. Because thorswap already supports ledger hardware wallet, offline signing should also be possible.

The good thing about offline signing is that it can survive deaths of hardware wallets. Hardware wallets come and go, but offline signing is independent of survival of hardware wallet manufacturers. Code maintenance should also be simpler for offline signing than for hardware wallets. It is a good backup security mechanism. Monero and pirate chain also support offline signing apart from hardware wallets.

**Comment by thorswapdev** [comment]
ledger will be supported for all chains soon

**Comment by crocket** [comment]
Are you saying that you wouldn't merge offline signing?
