### ISSUE TITLE
choose and customize stat cards in main page

### ISSUE THREAD

**Issue by SLjavad** [thorswap/thorswap-finance-app#247]
it can be useful if users have ability to choose specific stat cards they like to show in the main page 
there's many stat cards in stats page .. so users can choose the cards they want to display them in the main page
 
![image](https://user-images.githubusercontent.com/24592212/122712667-863db980-d279-11eb-932a-32fd8a4f58e1.png)

**Comment by bullishtrader** [comment]
Hey @SLjavad , this would be very cool.
Unfortunately is not possible atm, you don't have a profile to be customized.. so the UI is public and can't be customized by each user for now.

But we will improve for sure 🚀

**Comment by SLjavad** [comment]
Cannot be stored in local storage ? based on each browser !

**Comment by bullishtrader** [comment]
@SLjavad Probably, but we have only 1 request as of now.
if we get more requests we will considering implementing this, it's a minor UI change.
