### ISSUE TITLE
Ledger - View address on device

### ISSUE THREAD

**Issue by Mansarde** [thorswap/thorswap-finance-app#249]
At the moment the THORChain app on the Ledger Nano doesn't show the wallet address on the device.
It is only possible to see the address in the browser when connecting the Ledger to e.g. THORSwap.
For security reasons it would be useful if we could confirm the address on the device itself.

THORChain app version: 2.0.0

**Comment by bullishtrader** [comment]
Hi @Mansarde , you can confirm your address on Ledger with this button:

![Schermata 2021-07-01 alle 19 33 49](https://user-images.githubusercontent.com/82927810/124166914-b4a26c80-daa3-11eb-8ec0-48778a2354fa.png)

If you click on `Verify Address` your THOR Address will show up on your Ledger and you'll be able to confirm that both addresses match.

Have a great day ahead.

**Comment by Mansarde** [comment]
@bullishtrader 
Ah gotcha, wasn't aware of the icon performing that function.
Just tested it and works like a charm.
Thank you, much appreciated! 😊👍
