### ISSUE TITLE
Icon overlapping on Mobile

### ISSUE THREAD

**Issue by aang0203** [thorswap/thorswap-finance-app#25]
The Menu Icon is overlapping on Mobile
![THORSwap](https://user-images.githubusercontent.com/82150468/114011871-9ee32980-985d-11eb-96ea-4efb5cedeb0b.jpeg)

**Comment by skyorion427** [comment]
Fixed now.

**Comment by aang0203** [comment]
@skyorion427 thanks for fixing it. Great job!
