### ISSUE TITLE
Upgrade ETH RUNE fails when using Max button and Metamask

### ISSUE THREAD

**Issue by pmannle** [thorswap/thorswap-finance-app#250]
When on this page:

https://app.thorswap.finance/upgrade_rune

I'm connected with a Metamask account that has ETH RUNE in it, and I click Max, then Confirm, and the transactions fails. I've tried multiple times, and confirmed that I have enough ETH to cover the gas. 

Note that Metamask window doesn't pop-up to actually confirm; the transaction ledger in the top right just notes it as failed.

It works fine with less than the Max amount.

**Comment by bullishtrader** [comment]
Hi @pmannle the issue with the MAX button is a known issue, we are working on a fix.
