### ISSUE TITLE
Attempted to withdraw pending deposit. Thorswap withdrew entire LP instead (from a pending pool).

### ISSUE THREAD

**Issue by DreamboatCrypto** [thorswap/thorswap-finance-app#251]
When attempting to withdraw a pending deposit of LINK, thorswap returned my entire LP to me instead. Here is the sequence of events:

1. I attempted to create a LINK pool by depositing RUNE/LINK symmetrically.
2. The first attempt failed for whatever reason (possibly user error). My Rune was not deposited, and my 400 LINK ended up pending.
3. I attempted to create a LINK pool again using the same amount of RUNE/LINK. This one was successful.
4. I attempted to withdraw my pending LINK. This resulted in my entire LP being withdrawn, leaving the stuck LINK still pending.
5. I was able to withdraw the pending LINK successfully later.

![image](https://user-images.githubusercontent.com/85963056/123284902-3ad21800-d4d2-11eb-9350-3df5a00b9405.png)
The completed transaction above is this one: https://viewblock.io/thorchain/tx/3C2B94B944112C85E1CFAF9DF062E93E3E3B872ADD15D2755CD4C8980FF3F241

**Comment by DreamboatCrypto** [comment]
I should have mentioned: before the strange LP return, I was having this error when trying to withdraw my pending LINK: Out of gas in location: readflat.

This was addressed in support ticket: outofgas-1196.

**Comment by bullishtrader** [comment]
@DreamboatCrypto , Thanks for the report.

**Comment by UncleBadgers** [comment]
https://viewblock.io/thorchain/address/thor1n5ynn2dtxtghlhqpkrtfhmv9e2t9eljyfwk8gj

Here is the pending and LP deposit being withdrawn
![Screen Shot 2021-06-24 at 15 44 20](https://user-images.githubusercontent.com/84528871/123286732-12641100-d506-11eb-9ba2-e5275adf730d.png)

**Comment by DreamboatCrypto** [comment]
Is there any way for me to prove that I clicked the withdraw pending button from my side, rather than removing liquidity? Or can you guys see that somehow?

**Comment by bullishtrader** [comment]
user refunded / waiting for refund, i'll close this issue @DreamboatCrypto
