### ISSUE TITLE
Cannot withdraw funds using Ledger

### ISSUE THREAD

**Issue by MattyIce** [thorswap/thorswap-finance-app#252]
I tried to deposit liquidity in BUSD and RUNE with the RUNE held on a Ledger wallet and the BUSD in a keystore file wallet. The BUSD deposit was successful (see here for tx: https://viewblock.io/thorchain/tx/FDFEDFE0A1FD68BAF03C903BD73554D8567FCA3F5F1C5BA9ABD973D76CC639CD) but the RUNE deposit was not submitted because my ledger got disconnected. 

By this point the caps were reached so I tried to withdraw my pending BUSD deposit. I signed the transaction on my Ledger device but received a "Submit Transaction Failed" error on app.thorswap.finance. You can see this in the screenshot below:

![Capture](https://user-images.githubusercontent.com/2294614/123288857-edf43e80-d4dd-11eb-99f1-330e24f78fa5.PNG)

You can see the pending funds here: https://thornode.thorchain.info/thorchain/pool/BNB.BUSD-BD1/liquidity_provider/thor15tju4rmumzt676jwzuey2mmz33q4s47nkwt9sn

Please let me know if there is a way to withdraw my pending funds. Thank you.

**Comment by bullishtrader** [comment]
Hi @MattyIce Apparently the same issue is happening with TrustWallet and Keystore Wallet as of issue #261 

I've added the help wanted label for extra attention on this.
please keep following up this ticket here or the ticket on discord.

cc @UncleBadgers

**Comment by bullishtrader** [comment]
Hi @MattyIce , can you try to withdraw again?

Just to let you know, we pushed a new update today for Ledger pending deposits.

**Comment by MattyIce** [comment]
@bullishtrader it worked, thank you!! Thorswap website just shows the transaction as spinning but it appears to have gone through and the pending funds are back in my Binance wallet. The withdraw transaction is https://viewblock.io/thorchain/tx/B9A0BBBB251E7A0F979D4667CEEF07C9E3190C26844F8124F70B4DC58826EC26

I will close this ticket - awesome support also!

**Comment by bullishtrader** [comment]
Glad it worked out @MattyIce , yes i confirm there was a similar issue with another user.. tx was spinning but funds were returned to the wallet successfully.

have a great day :)
