### ISSUE TITLE
Swap message on top right hand corner always there.

### ISSUE THREAD

**Issue by runekeithrun** [thorswap/thorswap-finance-app#26]
![Capture5](https://user-images.githubusercontent.com/82149388/114012551-0b2f4e80-9899-11eb-9609-9afcd4f2489d.PNG)

![Capture6](https://user-images.githubusercontent.com/82149388/114012559-0cf91200-9899-11eb-8f3c-3f17326c6186.PNG)

After we have swap Rune for ETH, the top right hand corner message is always there and will not disappear even when we go to other pages.

**Comment by runekeithrun** [comment]
![image](https://user-images.githubusercontent.com/82149388/114015293-1b94f880-989c-11eb-8302-af40023def8c.png)

If user is unable to clear those message, it would cluster the interface

**Comment by aang0203** [comment]
you can hide the swap messages by hitting the top right button, but not sure if you can clear the messages themselves.

**Comment by runekeithrun** [comment]
can hide, but cannot clear

**Comment by skyorion427** [comment]
You can clear now.
