### ISSUE TITLE
Error withdrawing funds using Trust Wallet on Thorswap

### ISSUE THREAD

**Issue by Vaughnisa** [thorswap/thorswap-finance-app#261]
I keep my coins in TrustWallet 
52 days ago I learned that I can save the seed phrase from TrustWallet as a keystore and access the LP. I added LP several times with no problem. When I login to Thorswap with either Keystore (using TW phrase) or TW through WalletConnect I can see all of my assets, wallet and LP exactly the same. 
When I attempt to withdraw from the pools using WalletConnect, I'm receiving an error 

<img width="704" alt="Screen Shot 2021-06-25 at 8 18 56 AM" src="https://user-images.githubusercontent.com/86475364/123423793-ff951f00-d58d-11eb-9cfc-ac11139b4dc3.png">

<img width="952" alt="Screen Shot 2021-06-25 at 8 19 21 AM" src="https://user-images.githubusercontent.com/86475364/123423850-0e7bd180-d58e-11eb-875e-7cdfb3704abd.png">

I can still add/withdraw to that wallet without issues using the keystore

Discord: Vaughn#6445

**Comment by bullishtrader** [comment]
@thorswapdev , @0xMars4204 

When keystore Wallet option will be deprecated, users might be in trouble when withdrawing funds using TW.
I would add this to the list of the priorities.

@Vaughnisa Thank you for the report.

**Comment by kiasaki** [comment]
I actually hit the same error trying to withdraw using TrustWallet:

From the network tab, seems like you are trying to get the user's account info from a thornode using the `cosmos` prefixed bech32 address and not a `thor` prefixed one, the address doesn't match my actual thorchain address too.

URL: `https://thornode.thorchain.info/auth/accounts/cosmos1rrxy2w...`

Error message: `invalid Bech32 prefix; expected thor, got cosmos`

**Comment by bullishtrader** [comment]
@kiasaki , @Vaughnisa 

This is fixed now.
Please try again
