### ISSUE TITLE
Can't click the asset I want to swap

### ISSUE THREAD

**Issue by LM40357365** [thorswap/thorswap-finance-app#265]
Hey, small 'issue' I like to report.
When clicking on a pool I want to swap my asset to, I can only swap rune.
Only way to change the first asset is to click the following arrows:
![image](https://user-images.githubusercontent.com/84539729/123952430-4926a500-d9a6-11eb-8c38-c009654cd892.png)

Would be easier if you could click asset and change it for both assets in my opinion.
If it was done intentionally, consider this as unsent :)

**Comment by thorswapdev** [comment]
sounds reasonable

will fix

**Comment by bullishtrader** [comment]
Thanks for the report @LM40357365
