### ISSUE TITLE
Unable to add to liquidity

### ISSUE THREAD

**Issue by runekeithrun** [thorswap/thorswap-finance-app#29]
![image](https://user-images.githubusercontent.com/82149388/114014571-56e2f780-989b-11eb-8111-9e7f5d4a6dff.png)

We tried adding liquidity to Rune-BNB and Rune-BTC, and they are loading forever non-stop.

**Comment by runekeithrun** [comment]
![image](https://user-images.githubusercontent.com/82149388/114016929-fa350c00-989d-11eb-93b2-81cce658cc71.png)

No issue in adding liquidity for BUSD

**Comment by skyorion427** [comment]
There has been an issue in the BTC pool, it would be fine now.
