### ISSUE TITLE
Cannot add liquidity base on single asset

### ISSUE THREAD

**Issue by runekeithrun** [thorswap/thorswap-finance-app#30]
![image](https://user-images.githubusercontent.com/82149388/114015022-d670c680-989b-11eb-8665-a6f522589526.png)

Firstly, the slider bar is not working as it should be. And when we choose to add base on "Rune" only, the BCH does not reflect. And the loading on the right hand side is loading forever.

**Comment by skyorion427** [comment]
fixed
