### ISSUE TITLE
Once withdraw, Liquidity balance not updated

### ISSUE THREAD

**Issue by runekeithrun** [thorswap/thorswap-finance-app#32]
![image](https://user-images.githubusercontent.com/82149388/114018527-eb4f5900-989f-11eb-8194-81f256a6ec19.png)

![image](https://user-images.githubusercontent.com/82149388/114018558-f609ee00-989f-11eb-9a16-df62d5e6e4ea.png)

Once we initiated and completed the withdrawal, the balance is still showed as 170BUSD pooled asset. Despite we had withdraw multiples time, balance is still not updated. 

![image](https://user-images.githubusercontent.com/82149388/114018864-4c772c80-98a0-11eb-9e03-8c45589e2a2f.png)

![image](https://user-images.githubusercontent.com/82149388/114018926-5f89fc80-98a0-11eb-9386-292eb2d9d418.png)

**Comment by runekeithrun** [comment]
![image](https://user-images.githubusercontent.com/82149388/114019413-f22a9b80-98a0-11eb-81ff-53946a66c2f4.png)
![image](https://user-images.githubusercontent.com/82149388/114019432-fb1b6d00-98a0-11eb-8e99-f6d3828fc0e6.png)
![image](https://user-images.githubusercontent.com/82149388/114019449-01114e00-98a1-11eb-9586-f71e475848ca.png)

When we have withdraw everything from our pooled liquidity, the pooled asset is still shown. It should not be shown when we have 0 Rune and 0 BUSD that we can withdraw

**Comment by skyorion427** [comment]
fixed
