### ISSUE TITLE
Viewing Liquidity Tab Flow

### ISSUE THREAD

**Issue by thethorlady** [thorswap/thorswap-finance-app#36]
After I was looking at my ETH RUNE Pool - viewing liquidity,
then I click to Withdraw (third icon in the menu ribbon),
the screen shows I have no BTC liquidity, even know I wanted to look at my ETH liquidity.

Should it show my ETH:RUNE liquidity on this page?

<img width="439" alt="Screen Shot 2021-04-09 at 16 12 33" src="https://user-images.githubusercontent.com/81938319/114143117-b64e0f80-994e-11eb-8748-6475f57d06c6.png">

<img width="453" alt="Screen Shot 2021-04-09 at 16 12 46" src="https://user-images.githubusercontent.com/81938319/114143134-b9e19680-994e-11eb-9c98-bccaeb7b6457.png">

**Comment by skyorion427** [comment]
Good find.
