### ISSUE TITLE
Add LP Asymmetrically for RUNE uses Native asset in slider instead

### ISSUE THREAD

**Issue by thethorlady** [thorswap/thorswap-finance-app#39]
When trying to add RUNE asymmetrically to LP, the native asset's numbers change, instead of RUNE.

<img width="446" alt="Screen Shot 2021-04-09 at 16 18 52" src="https://user-images.githubusercontent.com/81938319/114143690-6b80c780-994f-11eb-92ee-ce5d02632542.png">

**Comment by pmannle** [comment]
Seems to be working now....
<img width="463" alt="Screen Shot 2021-04-12 at 6 16 29 PM" src="https://user-images.githubusercontent.com/6116644/114482376-560fd580-9bbb-11eb-87dd-53993f624d0e.png">
