### ISSUE TITLE
Search pool dont work

### ISSUE THREAD

**Issue by ricoCryptoboy** [thorswap/thorswap-finance-app#41]
Hi, when filling search input box for a token in pools it show nothing, (nor with few letter or full token name)

cheers

**Comment by ricoCryptoboy** [comment]
On IOS

**Comment by ricoCryptoboy** [comment]
![Uploading B5937CAF-C955-491C-8732-91B27A20D3B6.png…]()

**Comment by ricoCryptoboy** [comment]
![Uploading BD764A34-24C1-46D1-83C7-5FAACFBEC9F2.png…]()

**Comment by ricoCryptoboy** [comment]
Screenshot 
![Uploading 3DCAE1AE-C9BD-47CC-B4B4-2D28B203672A.png…]()

**Comment by skyorion427** [comment]
fixed
