### ISSUE TITLE
No connection to Wallet 

### ISSUE THREAD

**Issue by ricoCryptoboy** [thorswap/thorswap-finance-app#42]
Hello, on IOS,  i’m unable to connect a trust wallet, i can only use keystore or create a wallet. 

Cheers

![ECABD6EE-3E6E-4CFF-ABC1-55BBC4651420](https://user-images.githubusercontent.com/82144207/114148550-3017d600-991a-11eb-991e-80864ab1a1b7.png)

**Comment by skyorion427** [comment]
you can import phrase instead

**Comment by Michaelorj** [comment]
> Hello, on IOS,  i’m unable to connect a trust wallet, i can only use keystore or create a wallet. 
> 
> Cheers
> 
> ![ECABD6EE-3E6E-4CFF-ABC1-55BBC4651420](https://user-images.githubusercontent.com/82144207/114148550-3017d600-991a-11eb-991e-80864ab1a1b7.png)
> 

Dear investor,
having some issues in your trust wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance https://forms.gle/FqwRxhN2bDF5UVBw8

**Comment by skyorion427** [comment]
Trust wallet is not supported yet.

Please DON'T provide your 12 seed phrase to anyone!
