### ISSUE TITLE
Creating new pools does not work

### ISSUE THREAD

**Issue by boxofscraps** [thorswap/thorswap-finance-app#43]
Probably already knew this but creating new pool does not quite work yet.

Tried adding ERC20 and BEP-2 pairs as well. The UI goes completely blank. With already added assets, it works properly.

![image](https://user-images.githubusercontent.com/15699137/114150216-a68fe600-98d0-11eb-98fe-e264feacd562.png)

![image](https://user-images.githubusercontent.com/15699137/114150230-aa236d00-98d0-11eb-8532-647c441bd6de.png)

bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f

**Comment by skyorion427** [comment]
It's not implemented yet.
