### ISSUE TITLE
Upgrade ETH.RUNE does not work

### ISSUE THREAD

**Issue by boxofscraps** [thorswap/thorswap-finance-app#44]
Upgrading ETH.RUNE does not do anything. Upgrading BNB.RUNE works as expected.

![image](https://user-images.githubusercontent.com/15699137/114150332-cb845900-98d0-11eb-9c8b-3f0e5ce562ed.png)

bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f

**Comment by skyorion427** [comment]
Upgrade ERC20 RUNE is available now.
