### ISSUE TITLE
Thorchain Block Explorer

### ISSUE THREAD

**Issue by boxofscraps** [thorswap/thorswap-finance-app#45]
Go to account link currently redirects to:
https://testnet.thorchain.net/#/addresses/tthor1ruwh7nh8lsl3m5xn0rl404t5wjfgu4rmgz3e6w

The correct link should be:
https://testnet.thorchain.net/#/address/tthor1ruwh7nh8lsl3m5xn0rl404t5wjfgu4rmgz3e6w

bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f

**Comment by skyorion427** [comment]
should be fixed from `xchainjs` side
