### ISSUE TITLE
Single Sided Addition of Liquidity

### ISSUE THREAD

**Issue by boxofscraps** [thorswap/thorswap-finance-app#47]
Adding only one side of liquidity does not seem to work. It correctly allows users to add one asset and send the transaction but transaction never goes through.

![image](https://user-images.githubusercontent.com/15699137/114151012-87de1f00-98d1-11eb-9ab6-a05ee3ca59e8.png)

Withdrawing single sided liquidity shows both asset instead of just one.

![image](https://user-images.githubusercontent.com/15699137/114150990-80b71100-98d1-11eb-9083-4605f047f48d.png)

bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f

**Comment by skyorion427** [comment]
asymm withdraw will be implemented soon
