### ISSUE TITLE
Switching from Double to Single sided liquidity

### ISSUE THREAD

**Issue by boxofscraps** [thorswap/thorswap-finance-app#50]
When switching from double to single sided liquidity it would be nice if the other asset automatically reset to 0.  Currently, it stays fixed at the last quantity of asset.

![image](https://user-images.githubusercontent.com/15699137/114155762-b27ea680-98d6-11eb-9e6c-ab899c49570a.png)
 
![image](https://user-images.githubusercontent.com/15699137/114155791-bc080e80-98d6-11eb-9cda-3aaf719132b2.png)

**Comment by skyorion427** [comment]
fixed
