### ISSUE TITLE
Error: Withdraw liquidity doesn't link to tx explorer

### ISSUE THREAD

**Issue by thethorlady** [thorswap/thorswap-finance-app#56]
After the transaction is completed, I check the explorer but the links go here:

https://testnet.thorchain.net/#/txs/0000000000000000000000000000000000000000000000000000000000000000

<img width="317" alt="Screen Shot 2021-04-10 at 13 34 09" src="https://user-images.githubusercontent.com/81938319/114258457-8a3f9680-9a01-11eb-8c41-3871ad8a19c0.png">

**Comment by pmannle** [comment]
this looks fixed as well 🔥
<img width="1393" alt="Screen Shot 2021-04-12 at 6 19 26 PM" src="https://user-images.githubusercontent.com/6116644/114482644-c4ed2e80-9bbb-11eb-9a45-c6ca7c449c76.png">
