### ISSUE TITLE
Liquidity providing doesn't work. RUNE-BUSD pool providing/withdraw UI errors. Loss of liquidity

### ISSUE THREAD

**Issue by nikolasete** [thorswap/thorswap-finance-app#60]
1. I used https://app.thorswap.finance/add/BNB.BUSD-BD1 to provide BUSD-RUNE liquidity
2. First I suplied 499 BUSD - 7 RUNE. Tx: https://viewblock.io/thorchain/tx/F218C933F8A2F134FFDCF2FC285C0E0055187D434E779332CF025946F3F10E7A
3. I tried to withdraw 100% and got 288 BUSD - 22,7 RUNE. Tx: https://viewblock.io/thorchain/tx/F218C933F8A2F134FFDCF2FC285C0E0055187D434E779332CF025946F3F10E7A
4. It was a very strange behaviour. I assumed the "+15" RUNE added, may be the near "-210" BUSD disappeared.
5. I made another suply: 88 BUSD - 22 RUNE. Tx: https://viewblock.io/thorchain/tx/D43B115BF85860FCA28F6A366DC2823774FB6176F6F5F68846FC59972596FCAB
6. And the last withdraw, I received: 199 BUSD - 15,2 RUNE. Tx: https://viewblock.io/thorchain/tx/04107078B5F181BF8954AC41DECF965E36CBDCA2AE79A13CA44711E912B78AFA
7. All the times, the UI showed different amounts for the deposit and withdraw than the final suplied/received amounts.
8. Even more, after the last withdrawal, the UI showed an amount still deposited in the BUSD-RUNE pool, so I tried to withdraw, but errors prevented the wtihdraw. Tx: https://viewblock.io/thorchain/tx/715F4A467AC1F28F85D3409DC246674119127F0A0A5D8C8F7580F62CCC362534
9. I started with 40 RUNE - 499 BUSD and ended with 200 BUSD and 48 RUNE (loss near 80 BUSD)

**Comment by nikolasete** [comment]
Closed without comments?

**Comment by skyorion427** [comment]
deposit/withdraw UI has been fixed. Go checkout your Liquidity on thorswap or runeyield.info

**Comment by nikolasete** [comment]
Sorry, but there's an issue: Runeyield shows an active LP: https://app.runeyield.info/dashboard?thor=thor16tggfacyd3asjg5tastgyzrp58eakk9223ka9u
And thorswswap says "You don't have LP to withdraw".
So I have liquidity, but no way to withdraw.... :(
![Captura web_20-4-2021_223541_app runeyield info](https://user-images.githubusercontent.com/65187655/115460745-eb990e00-a228-11eb-8902-a33a89c3ed4c.jpeg)
![Captura web_20-4-2021_223830_app thorswap finance](https://user-images.githubusercontent.com/65187655/115460951-2bf88c00-a229-11eb-85a9-46de2918fd43.jpeg)

**Comment by skyorion427** [comment]
ok will investigate asap

**Comment by thorswapdev** [comment]
fixed now
