### ISSUE TITLE
Issues from asgard exchange

### ISSUE THREAD

**Issue by skyorion427** [thorswap/thorswap-finance-app#62]
https://github.com/asgardex/asgard-exchange/issues/267
https://github.com/asgardex/asgard-exchange/issues/260
https://github.com/asgardex/asgard-exchange/issues/257

**Comment by vaticanvoodoo** [comment]
Thank you for opening the issue on my behave in the correct repo.

**Comment by skyorion427** [comment]
Fixed.

**Comment by vaticanvoodoo** [comment]
> Fixed.

Is the fix in a coming build?  If so, any idea when it will be released?
