### ISSUE TITLE
btc amount added to the pool shows 0 when funds where added symetrically

### ISSUE THREAD

**Issue by vaticanvoodoo** [thorswap/thorswap-finance-app#65]
<img width="436" alt="Screen Shot 2021-04-14 at 1 53 59 PM" src="https://user-images.githubusercontent.com/37843387/114763938-fd5e4b00-9d28-11eb-9cc3-510d019802e5.png">
<img width="680" alt="Screen Shot 2021-04-13 at 5 07 47 PM" src="https://user-images.githubusercontent.com/37843387/114764037-18c95600-9d29-11eb-8517-3c70d42e9e29.png">

**Comment by skyorion427** [comment]
it's a too small amount, will be fixed soon

**Comment by vaticanvoodoo** [comment]
> it's a too small amount, will be fixed soon

It's not closed, because to add symmetrically, roughly .04 btc is needed to add roughly 200 rune, but as the screen shot shows above, it shows .0018 btc was added for to the pool when the submitting screen shows .04 is to be added.
![Uploading Screen Shot 2021-04-14 at 2.18.21 PM.png…]()
