### ISSUE TITLE
BNB liquidity provided but not displayed on Withdrawal page

### ISSUE THREAD

**Issue by kolya182** [thorswap/thorswap-finance-app#66]
Supplied 1 BNB liquidity but it show `You don't have any BNB liquidity.`
<img width="1618" alt="Screen Shot 2021-04-14 at 2 28 17 PM" src="https://user-images.githubusercontent.com/3277207/114781612-c0488780-9d2d-11eb-8dcd-00fbf22be88a.png">

**Comment by storm-breaker2** [comment]
refresh your BNB balance
