### ISSUE TITLE
Output exceeds minimum revert threshold

### ISSUE THREAD

**Issue by SP-Nate** [thorswap/thorswap-finance-app#70]
UX advised an exchange of 59 BUSD (BEP2) to a minimum of 58 USDT (ERC20)

Swap completed with delivery of 1 USDT, please investigate 

https://explorer.binance.org/tx/ECBC46BBAFE2F7CB515954ABFD1ADA5ECC5BA88A5E6DC438FA309AB950C6FAF6 OUT

https://etherscan.io/tx/0xa244888a0eeeda6206c4fe9397a2df16f1d8a30041c3729b047eaf30486695e9 IN

**Comment by SP-Nate** [comment]
If this is the case, should not the front end therefore have estimated the cost of gas for the transaction and have accurately advised that for a swap of 59 BUSD, the expected USDT to be received is 1, or 3, or whatever the values should have been?

this is extremely misleading - while I understand that gas fees can not be avoided and are part of life,  either the swap should match the declared transfer out and transfer in values on-screen (with gas costs occurring behind the scenes) or the gas costs should be estimated and rolled into the transfer-in value

**Comment by storm-breaker2** [comment]
Submitted request for that functionality: https://github.com/thorswap/thorswap-finance-app/issues/72

**Comment by thorswapdev** [comment]
fixed
