### ISSUE TITLE
Amount of BTC added to the BTC/RUNE pool does not match withdrawal from wallet.

### ISSUE THREAD

**Issue by vaticanvoodoo** [thorswap/thorswap-finance-app#71]
This the amount deducted from my wallet.
<img width="486" alt="Screen Shot 2021-04-15 at 10 49 02 AM" src="https://user-images.githubusercontent.com/37843387/114906035-41138c00-9ddf-11eb-804a-34eab2f505c9.png">

This is the amount show in the liquidity screen.
<img width="407" alt="Screen Shot 2021-04-15 at 11 40 51 AM" src="https://user-images.githubusercontent.com/37843387/114906251-77e9a200-9ddf-11eb-97e5-212ed68ec185.png">

This is what shows in the explorer.
<img width="584" alt="Screen Shot 2021-04-13 at 5 07 52 PM" src="https://user-images.githubusercontent.com/37843387/114906129-5be60080-9ddf-11eb-9a0d-e78cc857257c.png">

**Comment by storm-breaker2** [comment]
Based on your address, I think this was the transaction that sent your BTC. You can see it was for 0.02097 BTC. 
https://blockstream.info/tx/4e52f3bca9dbe28c45cc2a54afb4b40e06808dfcebd1e89b0bc9ac45563f8aa8

**Comment by vaticanvoodoo** [comment]
> Based on your address, I think this was the transaction that sent your BTC. You can see it was for 0.02097 BTC.
> https://blockstream.info/tx/4e52f3bca9dbe28c45cc2a54afb4b40e06808dfcebd1e89b0bc9ac45563f8aa8


I don't think that is right.  Here's the transaction:

<img width="678" alt="Screen Shot 2021-04-16 at 8 23 24 AM" src="https://user-images.githubusercontent.com/37843387/115030834-2566bf00-9e8d-11eb-8990-77251bb4b9cc.png">


There are two issues:

1)  Why is the symmetrical add is so unbalanced.  Adding 200 rune should be around .04 BTC.  Why would the UI say .04 BTC is needed to add 200 rune but only take .002??

<img width="392" alt="Screen Shot 2021-04-16 at 8 17 23 AM" src="https://user-images.githubusercontent.com/37843387/115030089-51ce0b80-9e8c-11eb-81f5-d6ae38d77fe1.png">

**Comment by storm-breaker2** [comment]
you can see the liquidity added here: 
https://app.runeyield.info/dashboard?btc=thor1dfgstlu6xk3dcsgkh0ssx4q22djgqu0a8y6pjc

**Comment by vaticanvoodoo** [comment]
So what you are saying is even though I tried to add 200 rune, it only actually added 100 rune?  The first screen shot in this thread shows 200, but I assume that's because it was a bug and it was actually 100?

**Comment by vaticanvoodoo** [comment]
Where did the 100 rune go?  Because I made two swaps at 100 rune and I thought I added 200 rune to the pool based on the first screenshot.  The other 100 rune is not in my wallet and it is not in the pool, so where did it go?

**Comment by vaticanvoodoo** [comment]
<img width="1055" alt="Screen Shot 2021-04-17 at 7 35 25 AM" src="https://user-images.githubusercontent.com/37843387/115113362-86ef6200-9f4f-11eb-996e-65484665f8c8.png">
 
Another view showing two swaps and then adding those two swaps to the pool.  Note the amounts.

**Comment by vaticanvoodoo** [comment]
I had someone explain to me that the 100 removed but I also gained a close equivalence of btc, so no funds are lost, I just wasn't expecting to see that big of a shift, but now I understand what happened.
