### ISSUE TITLE
ETH Send not working

### ISSUE THREAD

**Issue by Feedurhead-1** [thorswap/thorswap-finance-app#74]
Have tried multiple times to send eth and the site refreshes with no outcome or message, have tried with the max option and less than the total amount, results unchanged. 

I have balance on both rune and eth side.  
![image](https://user-images.githubusercontent.com/82659700/115030336-5d75fe00-9e9d-11eb-8d0e-59df0e12413e.png)

Tried again with even less, still same outcome. 
![image](https://user-images.githubusercontent.com/82659700/115030874-f573e780-9e9d-11eb-8b41-3f8a197496f5.png)

Cheers,

**Comment by storm-breaker2** [comment]
confirmed that is a problem right now.

**Comment by skyorion427** [comment]
FIxed.

**Comment by Feedurhead-1** [comment]
Thanks Guys!
