### ISSUE TITLE
Bitcoin sent to QR code and showing confirmed not displaying in UI. 

### ISSUE THREAD

**Issue by zackarychapple** [thorswap/thorswap-finance-app#75]
Yesterday using the QR code (image below) on the bitcoin portion of my wallet created on Thorswap from Coinbase to Thorswap. When I view the[ address on blockstream](https://blockstream.info/address/bc1qv7n9jlkpanp62h7z56mr3n2jmwdqnnqwszspgv) I see 1 confirmed transaction that is received and unspent. 

Is there a delay in the UI?  Trying to understand what's going on. 

![image](https://user-images.githubusercontent.com/2133184/115033800-d757b880-9e98-11eb-99de-0c4c108762b4.png)

**Comment by storm-breaker2** [comment]
Please refresh your your BTC balance and check again.

**Comment by zackarychapple** [comment]
just checked and still showing as 0.

**Comment by skyorion427** [comment]
should arrive once tx is confirmed
wallet is not more than interface and it fetches data from btc network

**Comment by zackarychapple** [comment]
@skyorion427 today I was able to see the btc on the site.  According to Jatin on the telgram there was a UI bug that kept the bitcoin from showing up.
