### ISSUE TITLE
Display ETH Fees

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#77]
Eth network fees are not being displayed during swaps or wallet transfers. 

![image](https://user-images.githubusercontent.com/82639838/115072055-e7c55e80-9eab-11eb-85f8-c9d5699e92a5.png)

![image](https://user-images.githubusercontent.com/82639838/115071989-d419f800-9eab-11eb-86ff-b6e188ae2215.png)

**Comment by thorswapdev** [comment]
fixed
