### ISSUE TITLE
ETH Transactions Explorer

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#78]
It links to https://ropsten.etherscan.io/tx/0x0x604043ddfb7a391fdf2948495804ac0dff1017a498bf77a6751d81873b9921a9

There is an extra 0x prefix.  Should be:
https://ropsten.etherscan.io/tx/0x604043ddfb7a391fdf2948495804ac0dff1017a498bf77a6751d81873b9921a9

![image](https://user-images.githubusercontent.com/82639838/115077980-cd8f7e80-9eb3-11eb-80c0-ef11c0d65b05.png)

**Comment by skyorion427** [comment]
Fixed
