### ISSUE TITLE
BNB send not working

### ISSUE THREAD

**Issue by archlinuxbeast** [thorswap/thorswap-finance-app#79]
I sent a test transaction to my binance chain wallet and it worked fine. But upon trying to send another transaction the page refreshes but no transaction is created and no message reported. Balance remains in my wallet. I've tried multiple times and nothing happens. I also can't swap my native rune back to BNB. Message comes up like it's working but the spinning pre-loader infinitely spins and viewing my wallet address shows no transaction. Are my coins just stuck temporarily?

Thanks,

**Comment by archlinuxbeast** [comment]
For anyone else with this issue. Turns out it was because I was sending the max amount of BNB which left none for the network fee. Subtracting the network fee from the total amount I was sending got it done. I assume that is probably my issue with swapping the rune back to bnb, but I'm gonna wait till my swap is profitable before trying it out with a small amount. Looking like it will be pretty soon and then I'll close this if it works out.

**Comment by skyorion427** [comment]
fixed now
