### ISSUE TITLE
Mobile UI won’t scroll down 

### ISSUE THREAD

**Issue by cburn12** [thorswap/thorswap-finance-app#8]
When accessing on mobile phone, can’t scroll down past the graphs showing volume. It gets stuck at a certain point and jumps back and forth to the top of screen

**Comment by cburn12** [comment]
https://user-images.githubusercontent.com/82137287/113977009-ee026d80-980f-11eb-8748-3f1695fc0609.mov

**Comment by skyorion427** [comment]
Fixed
