### ISSUE TITLE
Validation on Rune Withdraw address

### ISSUE THREAD

**Issue by danielalexiuc** [thorswap/thorswap-finance-app#82]
There doesn't seem to be any validation of the send address when using "Send Thor Rune".

I accidentally put a BEP2 address in there, and it created some kind of transaction on the thorchain network that I can't access.

Asgardex validates this address before sending, but thorswap finance doesn't, I think it needs to be added pretty urgently.

**Comment by tsarpaul** [comment]
Yep, I think I just lost money on this

**Comment by skyorion427** [comment]
reach out the team on telegram

**Comment by tsarpaul** [comment]
Butterfly told me to reach you out on Github..

**Comment by skyorion427** [comment]
THORSwap added the recipient address validation now.
