### ISSUE TITLE
Native Rune to BNB address

### ISSUE THREAD

**Issue by tsarpaul** [thorswap/thorswap-finance-app#83]
I sent Native RUNE to a BNB address through the THORSWAP web interface.
It created this transaction to this unrelated address:
https://viewblock.io/thorchain/tx/7540DBF810634C30920455AE5104569FA3C2F6E10C7BCA1A368FA6FA03797F76

I would've expected it to block me from sending the RUNE since the address should've been invalid (bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23).
Are the funds recoverable?

**Comment by therustymoose** [comment]
This same exact thing happened to me. I sent way to much money as well.

**Comment by therustymoose** [comment]
https://viewblock.io/thorchain/address/thor136ns6lfw4zs5hg4n85vdthaad7hq5m4g04w77q

This is the random address it went to. It looks like a few other people have had this happen as I'm not the first to send rune to this address.

**Comment by skyorion427** [comment]
fixed
