### ISSUE TITLE
Allowed to initiate multiple BTC to RUNE swaps using unconfirmed BTC balance

### ISSUE THREAD

**Issue by ianherri20** [thorswap/thorswap-finance-app#84]
I am using app.thorswap.finance to test swapping from native BTC to native RUNE.

Steps are as follows:

1. Sent a transaction to my BTC wallet that is connected to Thorswap for ~.018 BTC.
2. Balance appeared in my BTC wallet.
3. Transaction had not yet been confirmed on BTC chain.
4. Prior to BTC transaction confirmation, I was allowed to place a swap order for BTC to RUNE.
5. When I confirmed the swap, the 'swap dialog' box persisted, so I assumed it did not complete.
6. I clicked the 'swap' button again.
7. I now have 2 duplicate pending swaps from BTC to RUNE.
8. They are not completing because my BTC wallet does not have and BTC value yet (due to unconfirmed TX from step 3.)

**Comment by ianherri20** [comment]
![Image 4-19-21 at 10 23 AM](https://user-images.githubusercontent.com/49728899/115252243-4e8b8780-a0f9-11eb-9ae7-ac55649d006f.jpg)
here are the two duplicate swaps, pending for ~30 minutes.

**Comment by ianherri20** [comment]
![Image 4-19-21 at 10 24 AM](https://user-images.githubusercontent.com/49728899/115252491-84c90700-a0f9-11eb-98b8-e0cb6ff66ef4.jpg)
and here is my wallet, showing the BTC balance. Note this screenshot taken at a time when the balance still has not been confirmed on the BTC chain.

**Comment by skyorion427** [comment]
fixed
