### ISSUE TITLE
Upgrading to native RUNE

### ISSUE THREAD

**Issue by JimenezGSide** [thorswap/thorswap-finance-app#85]
Hi

Ive been trying for days now to upgrade both BNB.RUNE and ETH.RUNE but neither will do it from both Thorswap or Asgardex desktop.

In Thorswap I choose how much i want to upgrade and click upgrade but just get the spinning circles in the top right saying send .... BNB RUNE. But it never does.

In Asgardex it doesnt give me the option to upgrade ETH.RUNE and BNB.RUNE lets me get to the final point but when mouse hovers over upgrade button a no entry sign appears and cannot press it.

Anyone know a solution please?

Thanks

**Comment by storm-breaker2** [comment]
You need ETH to upgrade ETH.RUNE and BNB to upgrade BNB.RUNE.
