### ISSUE TITLE
Asymmetric Deposit

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#87]
Slider goes past balance of RUNE for user. Currently the slider goes up to the equivalent RUNE of base asset. 

![image](https://user-images.githubusercontent.com/82639838/115329054-8bca3680-a146-11eb-87d4-412b9de54adc.png)

**Comment by storm-breaker2** [comment]
Also affects symmetric deposits. However, it does correctly throw out error when rune needed is below rune balance. 

![image](https://user-images.githubusercontent.com/82639838/115329316-fe3b1680-a146-11eb-89d4-241f5ab4db71.png)

**Comment by skyorion427** [comment]
Fixed
