### ISSUE TITLE
Liquidity Not Updating

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#88]
User's liquidity does not update after withdrawing assets. I withdraw all my BUSD assets and refreshed all the wallet balances but liquidity still shows the previous amount. 

![image](https://user-images.githubusercontent.com/82639838/115329845-c6809e80-a147-11eb-8b7f-f9f9ca4feb9c.png)

**Comment by skyorion427** [comment]
Fixed
