### ISSUE TITLE
Symmetrical Deposits [Bug]

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#89]
Symmetrical Deposits are still allowed even though there is not sufficient RUNE.  It does popup a Transaction Failed, however the base asset has already been sent.  Rune deposit is insufficient so is not sent.  

https://tltc.bitaps.com/d4fd28fba41df9cb4d0f874d679bce005c006e2ae47d89f3615810377c768636/tltc1q3pz6939wghmjaantp005f06u8t43a5tn697q8v

![image](https://user-images.githubusercontent.com/82639838/115482638-01480c80-a204-11eb-84a5-7b1a6c1d6842.png)

This causes user funds to be stuck waiting for symmetrical RUNE deposit.

**Comment by skyorion427** [comment]
fixed
