### ISSUE TITLE
Asymmetric Withdraw  [BUG]

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#91]
When user deposits using base asset, the UI should not allow the user to withdraw in RUNE.  The UI states the user will receive RUNE when this is not true. The transaction will result in the base asset being withdrawn which is the correct behavior. 

![image](https://user-images.githubusercontent.com/82639838/115484348-87198700-a207-11eb-8158-aa1992825420.png)

**Comment by storm-breaker2** [comment]
It should be defaulted and fixed such that DA withdraw is the only option available. 

![Uploading image.png…]()

**Comment by skyorion427** [comment]
Fixed
