### ISSUE TITLE
Unconfirmed Deposits Shown in User's Balance

### ISSUE THREAD

**Issue by storm-breaker2** [thorswap/thorswap-finance-app#92]
After the swap is received but still pending, refreshing the wallet balance shows the updated amount.  However, this balance is inaccurate because the balance is still pending and cannot be sent out yet. 

![image](https://user-images.githubusercontent.com/82639838/115529674-f31bdf80-a247-11eb-977a-296c6c619b43.png)

This confuses the users into thinking the assets are in their wallet already.

**Comment by storm-breaker2** [comment]
https://github.com/thorswap/thorswap-finance-app/issues/84

**Comment by skyorion427** [comment]
fixed
